/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AlertBanner: typeof import('./src/components/alerts/AlertBanner.vue')['default']
    Comment: typeof import('./src/components/Posts/Comment.vue')['default']
    ConfirmationDialog: typeof import('./src/components/Profile/components/ConfirmationDialog.vue')['default']
    EditProperty: typeof import('./src/components/Profile/components/EditProperty.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Login: typeof import('./src/components/Authentication/Login.vue')['default']
    Logout: typeof import('./src/components/Authentication/Logout.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    NewComment: typeof import('./src/components/Posts/NewComment.vue')['default']
    NewSpace: typeof import('./src/components/spaces/NewSpace.vue')['default']
    Post: typeof import('./src/components/Posts/Post.vue')['default']
    PostDetails: typeof import('./src/components/Posts/PostDetails.vue')['default']
    PostWriting: typeof import('./src/components/Posts/PostWriting.vue')['default']
    Profile: typeof import('./src/components/Profile/Profile.vue')['default']
    Register: typeof import('./src/components/Authentication/Register.vue')['default']
    ReturnBtn: typeof import('./src/components/ReturnBtn.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SavedPosts: typeof import('./src/components/Posts/SavedPosts.vue')['default']
    SearchBar: typeof import('./src/components/spaces/SearchBar.vue')['default']
    SnackbarMessage: typeof import('./src/components/alerts/SnackbarMessage.vue')['default']
    SpaceElement: typeof import('./src/components/spaces/SpaceElement.vue')['default']
    SpacesList: typeof import('./src/components/spaces/SpacesList.vue')['default']
    SpaceTimeline: typeof import('./src/components/spaces/SpaceTimeline.vue')['default']
    Timeline: typeof import('./src/components/Posts/Timeline.vue')['default']
    UserHeader: typeof import('./src/components/Profile/components/UserHeader.vue')['default']
    UserNotFound: typeof import('./src/components/Profile/components/UserNotFound.vue')['default']
    UserProfile: typeof import('./src/components/Profile/UserProfile.vue')['default']
    UserSettings: typeof import('./src/components/Profile/components/UserSettings.vue')['default']
    UserTimeline: typeof import('./src/components/Posts/UserTimeline.vue')['default']
  }
}
