/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AlertBanner: typeof import('./src/components/AlertBanner.vue')['default']
    Comment: typeof import('./src/components/Comment.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    Logout: typeof import('./src/components/Logout.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    Post: typeof import('./src/components/Post.vue')['default']
    PostDetails: typeof import('./src/components/PostDetails.vue')['default']
    PostWriting: typeof import('./src/components/PostWriting.vue')['default']
    Profile: typeof import('./src/components/Profile.vue')['default']
    Register: typeof import('./src/components/Register.vue')['default']
    ReturnBtn: typeof import('./src/components/ReturnBtn.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Timeline: typeof import('./src/components/Timeline.vue')['default']
  }
}
