version: '3.0'

services:
  neurona-api-service:
    build: ./docker-images/django
    container_name: neurona-django
    ports:
      - 8000:8000

    volumes: 
      - ./api/:/data 

    environment:
      - PASSKEY_RP_ID=localhost
      - PASSKEY_ORIGIN=localhost:3000
      - ALLOWED_HOSTS=localhost,
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
      - DATABASE_ENGINE=django.db.backends.postgresql
      - DATABASE_HOST=neurona-db-service
      - DATABASE_PORT=5432
      - DATABASE_NAME=neurona
      - DATABASE_USER=neurona
      - DATABASE_PASSWORD=password
      - DEBUG=True

  neurona-vuejs-service:
    build: ./docker-images/vuejs
    container_name: neurona-vuejs
    ports:
      - 5173:5173
      - 3000:3000

    volumes:
      - ./frontend:/data

    environment:
      - VITE_API_URL=http://localhost:8000/api

  neurona-db-service:
    container_name: neurona-postgres
    image: postgres:latest
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: neurona
      POSTGRES_USER: neurona
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  neurona-adminer-service:
    container_name: neurona-adminer
    image: adminer:latest
    ports:
      - "8080:8080"
