version: '3.0'

services:
  api:
    build: ./docker-images/django
    container_name: neurona-django
    ports:
      - 8000:8000

    volumes: 
      - ./api/:/data 

  vuejs:
    build: ./docker-images/vuejs
    container_name: neurona-vuejs
    ports:
      - 5173:5173
      - 3000:3000

    volumes:
      - ./frontend:/data

