version: '3.0'

services:
  neurona_api_service:
    build: ./docker-images/django
    container_name: neurona-django
    ports:
      - 8000:8000

    volumes: 
      - ./api/:/data 

  neurona_vuejs_service:
    build: ./docker-images/vuejs
    container_name: neurona-vuejs
    ports:
      - 5173:5173
      - 3000:3000

    volumes:
      - ./frontend:/data

  neurona_db_service:
    container_name: neurona-postgres
    image: postgres:latest
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: neurona
      POSTGRES_USER: neurona
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  neurona_adminer_service:
    container_name: neurona-adminer
    image: adminer:latest
    ports:
      - "8080:8080"
