# Generated by Django 5.0.2 on 2024-02-27 21:28

import neuronaApp.models.spaces_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuronaApp', '0002_spaces_alter_recoverycodes_user_apikeys_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spaces',
            name='privacy',
            field=models.CharField(choices=[(neuronaApp.models.spaces_models.Privacy['PUBLIC'], 'public'), (neuronaApp.models.spaces_models.Privacy['PROTECTED'], 'protected'), (neuronaApp.models.spaces_models.Privacy['RESTRICTED'], 'restricted'), (neuronaApp.models.spaces_models.Privacy['PRIVATE'], 'private')], max_length=100),
        ),
    ]
