# Generated by Django 5.0.2 on 2024-03-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuronaApp', '0004_commentsvotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenges',
            name='challenge',
            field=models.BinaryField(),
        ),
    ]
