# Generated by Django 5.0.2 on 2024-03-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuronaApp', '0005_alter_challenges_challenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publickeys',
            name='credential_id',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='publickeys',
            name='key',
            field=models.BinaryField(),
        ),
    ]
