# Generated by Django 5.0.2 on 2024-03-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuronaApp', '0006_alter_publickeys_credential_id_alter_publickeys_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
