# Generated by Django 5.0.2 on 2024-03-10 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neuronaApp', '0007_alter_user_display_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='passkey_user_id',
        ),
    ]
