# Generated by Django 5.0.2 on 2024-03-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuronaApp', '0008_remove_user_passkey_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='publickeys',
            name='sign_count',
            field=models.IntegerField(default=0),
        ),
    ]
