# Generated by Django 5.0.2 on 2024-03-14 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neuronaApp', '0009_publickeys_sign_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publickeys',
            name='sign_count',
        ),
    ]
