# Generated by Django 5.0.2 on 2024-03-18 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuronaApp', '0010_remove_publickeys_sign_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='space',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='neuronaApp.spaces'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='neuronaApp.tags'),
        ),
    ]
