# Generated by Django 5.0.2 on 2024-04-09 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neuronaApp', '0011_alter_posts_space_alter_posts_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
