# Generated by Django 5.0.2 on 2024-05-02 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuronaApp', '0013_savedposts'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image_urls',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='PostsImages',
        ),
    ]
