# Generated by Django 5.0.2 on 2024-05-02 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neuronaApp', '0014_alter_spaces_privacy'),
        ('neuronaApp', '0014_posts_image_urls_delete_postsimages'),
    ]

    operations = [
    ]
