# Generated by Django 5.0.2 on 2024-05-02 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuronaApp', '0015_merge_20240502_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='image_urls',
        ),
        migrations.CreateModel(
            name='PostsImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='neuronaApp.posts')),
            ],
        ),
    ]
