# Generated by Django 5.0.2 on 2024-03-06 18:23

import neuronaLogs.models.logs_models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CommentImagesLogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment_id", models.IntegerField()),
                ("image_url", models.URLField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="CommentLogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment_id", models.IntegerField()),
                ("user_id", models.IntegerField()),
                ("post_id", models.IntegerField()),
                ("content", models.TextField(max_length=1000)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            (
                                neuronaLogs.models.logs_models.CommentAction["CREATED"],
                                "created",
                            ),
                            (
                                neuronaLogs.models.logs_models.CommentAction["DELETED"],
                                "deleted",
                            ),
                        ],
                        max_length=100,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="CommentVoteLogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("comment_id", models.IntegerField()),
                (
                    "action",
                    models.CharField(
                        choices=[
                            (
                                neuronaLogs.models.logs_models.VoteAction["UPVOTED"],
                                "upvoted",
                            ),
                            (
                                neuronaLogs.models.logs_models.VoteAction["DOWNVOTED"],
                                "downvoted",
                            ),
                            (
                                neuronaLogs.models.logs_models.VoteAction[
                                    "CANCELLED_UPVOTE"
                                ],
                                "cancelled_upvote",
                            ),
                            (
                                neuronaLogs.models.logs_models.VoteAction[
                                    "CANCELLED_DOWNVOTE"
                                ],
                                "cancelled_downvote",
                            ),
                        ],
                        max_length=100,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="LoginLogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                (
                    "action",
                    models.CharField(
                        choices=[
                            (
                                neuronaLogs.models.logs_models.LoginAction["LOGGED_IN"],
                                "logged_in",
                            ),
                            (
                                neuronaLogs.models.logs_models.LoginAction[
                                    "LOGGED_IN_WITH_RECOVERY_CODE"
                                ],
                                "logged_in_with_recovery_code",
                            ),
                            (
                                neuronaLogs.models.logs_models.LoginAction[
                                    "LOGGED_OUT"
                                ],
                                "logged_out",
                            ),
                            (
                                neuronaLogs.models.logs_models.LoginAction[
                                    "FAILED_LOGIN"
                                ],
                                "failed_login",
                            ),
                        ],
                        max_length=100,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PostImagesLogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_id", models.IntegerField()),
                ("image_url", models.URLField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PostLogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_id", models.IntegerField()),
                ("user_id", models.IntegerField()),
                ("admin_id", models.IntegerField()),
                ("content", models.TextField(max_length=1000)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            (
                                neuronaLogs.models.logs_models.PostAction["CREATED"],
                                "created",
                            ),
                            (
                                neuronaLogs.models.logs_models.PostAction["DELETED"],
                                "deleted",
                            ),
                            (
                                neuronaLogs.models.logs_models.PostAction["ARCHIVED"],
                                "archived",
                            ),
                        ],
                        max_length=100,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PostVoteLogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("post_id", models.IntegerField()),
                (
                    "action",
                    models.CharField(
                        choices=[
                            (
                                neuronaLogs.models.logs_models.VoteAction["UPVOTED"],
                                "upvoted",
                            ),
                            (
                                neuronaLogs.models.logs_models.VoteAction["DOWNVOTED"],
                                "downvoted",
                            ),
                            (
                                neuronaLogs.models.logs_models.VoteAction[
                                    "CANCELLED_UPVOTE"
                                ],
                                "cancelled_upvote",
                            ),
                            (
                                neuronaLogs.models.logs_models.VoteAction[
                                    "CANCELLED_DOWNVOTE"
                                ],
                                "cancelled_downvote",
                            ),
                        ],
                        max_length=100,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SpaceAccessRequestLogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("space_id", models.IntegerField()),
                ("admin_id", models.IntegerField()),
                (
                    "action",
                    models.CharField(
                        choices=[
                            (
                                neuronaLogs.models.logs_models.SpaceAccessRequestAction[
                                    "ACCEPTED"
                                ],
                                "accepted",
                            ),
                            (
                                neuronaLogs.models.logs_models.SpaceAccessRequestAction[
                                    "REJECTED"
                                ],
                                "rejected",
                            ),
                            (
                                neuronaLogs.models.logs_models.SpaceAccessRequestAction[
                                    "CANCELLED"
                                ],
                                "cancelled",
                            ),
                            (
                                neuronaLogs.models.logs_models.SpaceAccessRequestAction[
                                    "SENT"
                                ],
                                "sent",
                            ),
                        ],
                        max_length=100,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SpaceAdminLogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("space_id", models.IntegerField()),
                ("admin_id", models.IntegerField()),
                (
                    "action",
                    models.CharField(
                        choices=[
                            (
                                neuronaLogs.models.logs_models.SpaceAdminAction[
                                    "ADDED"
                                ],
                                "added",
                            ),
                            (
                                neuronaLogs.models.logs_models.SpaceAdminAction[
                                    "REMOVED"
                                ],
                                "removed",
                            ),
                            (
                                neuronaLogs.models.logs_models.SpaceAdminAction["LEFT"],
                                "left",
                            ),
                        ],
                        max_length=100,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SpaceLogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("space_id", models.IntegerField()),
                ("name", models.CharField(max_length=100)),
                ("about", models.TextField(blank=True, max_length=2000)),
                ("image_url", models.URLField(null=True)),
                (
                    "privacy",
                    models.CharField(
                        choices=[
                            (
                                neuronaLogs.models.logs_models.Privacy["PUBLIC"],
                                "public",
                            ),
                            (
                                neuronaLogs.models.logs_models.Privacy["PROTECTED"],
                                "protected",
                            ),
                            (
                                neuronaLogs.models.logs_models.Privacy["RESTRICTED"],
                                "restricted",
                            ),
                            (
                                neuronaLogs.models.logs_models.Privacy["PRIVATE"],
                                "private",
                            ),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            (
                                neuronaLogs.models.logs_models.SpaceAction["CREATED"],
                                "created",
                            ),
                            (
                                neuronaLogs.models.logs_models.SpaceAction["DELETED"],
                                "deleted",
                            ),
                            (
                                neuronaLogs.models.logs_models.SpaceAction[
                                    "CHANGED_NAME"
                                ],
                                "changed_name",
                            ),
                            (
                                neuronaLogs.models.logs_models.SpaceAction[
                                    "CHANGED_ABOUT"
                                ],
                                "changed_about",
                            ),
                            (
                                neuronaLogs.models.logs_models.SpaceAction[
                                    "CHANGED_IMAGE"
                                ],
                                "changed_image",
                            ),
                            (
                                neuronaLogs.models.logs_models.SpaceAction[
                                    "CHANGED_PRIVACY"
                                ],
                                "changed_privacy",
                            ),
                        ],
                        max_length=100,
                    ),
                ),
                ("admin_id", models.IntegerField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SpaceMemberLogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("space_id", models.IntegerField()),
                ("admin_id", models.IntegerField()),
                (
                    "action",
                    models.CharField(
                        choices=[
                            (
                                neuronaLogs.models.logs_models.SpaceMemberAction[
                                    "JOINED"
                                ],
                                "joined",
                            ),
                            (
                                neuronaLogs.models.logs_models.SpaceMemberAction[
                                    "LEFT"
                                ],
                                "left",
                            ),
                            (
                                neuronaLogs.models.logs_models.SpaceMemberAction[
                                    "KICKED"
                                ],
                                "kicked",
                            ),
                            (
                                neuronaLogs.models.logs_models.SpaceMemberAction[
                                    "INVITED"
                                ],
                                "invited",
                            ),
                        ],
                        max_length=100,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TagLogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag_id", models.IntegerField()),
                ("space_id", models.IntegerField()),
                ("admin_id", models.IntegerField()),
                ("name", models.CharField(max_length=100)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            (
                                neuronaLogs.models.logs_models.TagAction["CREATED"],
                                "created",
                            ),
                            (
                                neuronaLogs.models.logs_models.TagAction["DELETED"],
                                "deleted",
                            ),
                            (
                                neuronaLogs.models.logs_models.TagAction[
                                    "CHANGED_NAME"
                                ],
                                "changed_name",
                            ),
                        ],
                        max_length=100,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserLogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("email", models.EmailField(max_length=100)),
                ("display_name", models.CharField(max_length=100)),
                ("username", models.CharField(max_length=100)),
                ("about", models.TextField(blank=True, max_length=2000)),
                ("image_url", models.URLField(null=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            (
                                neuronaLogs.models.logs_models.UserAction["CREATED"],
                                "created",
                            ),
                            (
                                neuronaLogs.models.logs_models.UserAction["DELETED"],
                                "deleted",
                            ),
                            (
                                neuronaLogs.models.logs_models.UserAction[
                                    "CHANGED_EMAIL"
                                ],
                                "changed_email",
                            ),
                            (
                                neuronaLogs.models.logs_models.UserAction[
                                    "CHANGED_DISPLAY_NAME"
                                ],
                                "changed_display_name",
                            ),
                            (
                                neuronaLogs.models.logs_models.UserAction[
                                    "CHANGED_USERNAME"
                                ],
                                "changed_username",
                            ),
                            (
                                neuronaLogs.models.logs_models.UserAction[
                                    "CHANGED_ABOUT"
                                ],
                                "changed_about",
                            ),
                            (
                                neuronaLogs.models.logs_models.UserAction[
                                    "CHANGED_IMAGE"
                                ],
                                "changed_image",
                            ),
                        ],
                        max_length=100,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
