# Generated by Django 5.0.2 on 2024-03-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neuronaLogs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentlogs",
            name="comment_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="postlogs",
            name="admin_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="postlogs",
            name="post_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="spacelogs",
            name="space_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="taglogs",
            name="tag_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="userlogs",
            name="user_id",
            field=models.IntegerField(null=True),
        ),
    ]
